### ISSUE TITLE
Documentation for how to edit the pelican site

### ISSUE THREAD

**Issue by arthurzenika** [YunoHost-Apps/pelican_ynh#4]
Great to see pelican be installable on yunohost. Once installed, how does one modify the site ? git / ssh / mercurial ?

**Comment by YliesC** [comment]
Sorry for the late answer I didn't check my notification before.
About your question, it's as you want, I personally use SSH to connect and edit what I want but feel free to take the easiest way for yourself.

In your case, what do you want to modify (content, config ...)?

**Comment by arthurzenika** [comment]
Yes, content and config.

**Comment by YliesC** [comment]
Did you ever used pelican by your own or is it the first time ?
You can check the official doc ([Content](http://docs.getpelican.com/en/3.6.3/content.html) / [Settings](http://docs.getpelican.com/en/3.6.3/settings.html)) to learn some basic concepts and ask here for specific questions if you struggle getting what you want.

Every contents (pages & articles) will be stored in the content folder (**/var/www/pelican/content**), the configuration file is pelicanconf.py but you can create your own and pass it as an argument when generating you website.

**Comment by arthurzenika** [comment]
I have already used pelican, I think I would expect a pelican ynh app to provide some sort of "git/mercurial" push + build kind of mecanism. If this is not planned (which is fine) maybe the README should inform the users about who to update their content.

**Comment by YliesC** [comment]
It's definitely not planned, setting up a git repository with your own content inside and an hook that trigger your build is leave to the end user (no right or better way to do).

Yunohost's apps aren't supposed to provide such mechanism tho, but just to provide the app as it could be installed on any server after following the official documentation.
I therefore see no point in adding such information that can be found on the official website (cf links above).

But if you really want it, feel free to make a pull request on that open sourced repository to share with the community.
